In [2]:
import numpy as np

In [3]:
# make a vector in np - 1D tensor
import numpy as np

v = np.array([5,2,1])

print(v, v.shape)

[5 2 1] (3,)


In [4]:
# element access in a vector
v[1]

2

In [5]:
# making a 2d tensor out of the same data (aka a row a matrix)
# this dimension (or higher) is needed for ML frameworks!
v = np.array([[5, 2, 1]])

print(v.shape)  # now we are saying we have at least 1 sample, 
# with the 3 elements 
# as features

(1, 3)


In [6]:
# how it's stored in memory
print(v)
# elements accessed from a matrix
print(v[0])

[[5 2 1]]
[5 2 1]


In [7]:
# converting the matrix to a column vector
v_t = np.transpose(v)

print(v_t)

print(f"Shape: {v_t.shape}")

[[5]
 [2]
 [1]]
Shape: (3, 1)


In [8]:
# Notice accesing elements has changed 
# v_t[1] - throws error

# second eelemnt is INSTEAD
v_t[1][0]

2

In [9]:
# Make a matrix 
v = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
# diff between shape and size

print(v.size)  # num of elem
print(v.shape)  # prints dims

6
(2, 3)


In [11]:
# What happens if we transpose?
# the rows and cols are switches...
# each column turns into a corresponding row!
# we call this a column matrix
v_t = np.transpose(v)
print(v_t)
print(v_t.size)
print(v_t.shape)

[[1 4]
 [2 5]
 [3 6]]
6
(3, 2)


In [12]:
# Arrange or Reshape the Matrix

v = np.array([[1,2,3],[2, 0, 1]])
print(v.reshape(3,2))

# By applying the following reshape, we transform the matrix into 3D Tensor

print(v.reshape(3,1,2))
print(v.reshape(-1,1,2))

[[1 2]
 [3 2]
 [0 1]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]


In [16]:
# make a 3d tensor
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)
print(v[0])
"""
# The first element of shape shows how many, and the second and third elements shows the dimension
print(v.shape)

print(v[0])

print(v[1])

print(v[2])

print(v.size)

print(v.reshape(3,2,-1))

print(v.reshape(3,-1,1))"""

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]
[[1. 2. 3.]
 [4. 5. 6.]]


'\n# The first element of shape shows how many, and the second and third elements shows the dimension\nprint(v.shape)\n\nprint(v[0])\n\nprint(v[1])\n\nprint(v[2])\n\nprint(v.size)\n\nprint(v.reshape(3,2,-1))\n\nprint(v.reshape(3,-1,1))'

In [14]:
# transformsing to  1d tensoe = lots of possibilities

a = v.reshape(1, 12)
a

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.]])

In [15]:
b = v.reshape(12, 1)
b

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [11.],
       [12.],
       [13.]])

In [18]:
# 4D tensor in numpy
v = np.zeros((2, 3, 5, 5))
print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [19]:
# Element Wise vs Matrix Multiplication
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(np.multiply(a,b))
print(np.multiply(b,a))
print(a*b)
print(b*a)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [20]:
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [21]:
print(np.dot(b, a))

[[23 34]
 [31 46]]


## Neural Network in Numpy

In [22]:
import numpy as np

# check this out:
# https://www.analyticsvidhya.com/blog/2017/05/neural-network-from-scratch-in-python-and-r/
# Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])


#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))


#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)



#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))


for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    D = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = D * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

print(output)

[[0.97838351]
 [0.96892906]
 [0.04054041]]


In [30]:
def f(x):
    return x*x

def calculate_der(x):
    """This is the SCALABLE way to calculate a numerical value for a derivative."""
    eps = 0.00000000005
    return (f(x + eps) - f(x)) / eps

print(calculate_der(3))

6.000000496442226
