In [15]:
import numpy as np

In [16]:
# make a vector in np - 1D tensor
import numpy as np

v = np.array([5,2,1])

print(v, v.shape)

[5 2 1] (3,)


In [17]:
# element access in a vector
v[1]

2

In [18]:
# making a 2d tensor out of the same data (aka a row a matrix)
# this dimension (or higher) is needed for ML frameworks!
v = np.array([[5, 2, 1]])

print(v.shape)  # now we are saying we have at least 1 sample, 
# with the 3 elements 
# as features

(1, 3)


In [19]:
# how it's stored in memory
print(v)
# elements accessed from a matrix
print(v[0])

[[5 2 1]]
[5 2 1]


In [20]:
# converting the matrix to a column vector
v_t = np.transpose(v)

print(v_t)

print(f"Shape: {v_t.shape}")

[[5]
 [2]
 [1]]
Shape: (3, 1)


In [21]:
# Notice accesing elements has changed 
# v_t[1] - throws error

# second eelemnt is INSTEAD
v_t[1][0]

2

In [22]:
# Make a matrix 
v = np.array([[1, 2, 3], [4, 5, 6]])

In [23]:
# diff between shape and size

print(v.size)  # num of elem
print(v.shape)  # prints dims

6
(2, 3)


In [24]:
# What happens if we transpose?
# the rows and cols are switches...
# each column turns into a corresponding row!
# we call this a column matrix
v_t = np.transpose(v)
print(v_t)
print(v_t.size)
print(v_t.shape)

[[1 4]
 [2 5]
 [3 6]]
6
(3, 2)


In [26]:
# Arrange or Reshape the Matrix

v = np.array([[1,2,3],[2, 0, 1]])
print(v.reshape(3,2))

# By applying the following reshape, we transform the matrix into 3D Tensor

print(v.reshape(3,1,2))
print(v.reshape(-1,1,2))

[[1 2]
 [3 2]
 [0 1]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]


In [29]:
# make a 3d tensor
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)
"""
# The first element of shape shows how many, and the second and third elements shows the dimension
print(v.shape)

print(v[0])

print(v[1])

print(v[2])

print(v.size)

print(v.reshape(3,2,-1))

print(v.reshape(3,-1,1))"""

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]


'\n# The first element of shape shows how many, and the second and third elements shows the dimension\nprint(v.shape)\n\nprint(v[0])\n\nprint(v[1])\n\nprint(v[2])\n\nprint(v.size)\n\nprint(v.reshape(3,2,-1))\n\nprint(v.reshape(3,-1,1))'

In [30]:
# transformsing to  1d tensoe = lots of possibilities

a = v.reshape(1, 12)
a

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.]])

In [31]:
b = v.reshape(12, 1)
b

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [11.],
       [12.],
       [13.]])